# For more information: https://laravel.com/docs/sail
version: '3'
services:
    carstory_api:
        build:
            context: ./
            dockerfile: Dockerfile.prod
        expose:
            - "80"
        depends_on:
            - carstory_db
        environment: 
            VIRTUAL_HOST: api.carstory.mdomzalski.pl,www.api.carstory.mdomzalski.pl
            LETSENCRYPT_HOST: api.carstory.mdomzalski.pl,www.api.carstory.mdomzalski.pl
        restart: always
    carstory_db:
        image: 'mysql:8.0'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'db_data:/var/lib/mysql'
        restart: always

volumes:
    db_data:

networks:
    default:
        external:
            name: nginx-proxy
